# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c0d4caeff8d7e73b6832eebb0fd96738036b111629784f8905f254cc21b6a3c83b3062a4a3b27944614d8bca5f1ae2898c0eeb09797b48f83081fbe966ac6565

test:
  secret_key_base: 5f2743b3941e00eb48968f47de7b2046615ab03fcf915dbe4083fb3230350ceb66c0c5a3bea661cacd8b200c417ce17e98fdc6ce7eee1d51415f38ac10b9f54f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
